#!/bin/bash

for i in {1..10..1};do
    curl -s \
         -X POST \
         -H 'Content-Type: application/json' \
         -d "{ \"username\": \"pr$i\", \
               \"password\": \"$(echo $i | md5sum | awk '{printf $1}')\" }" \
         http://localhost:8080/users
done
